server:
 port: 8085
my:
 greeting: HellllloooConfig
spring:
 application:
  name: FriendlyFoodsConfig
dbValues: "{connectionString: 'http://___', userName: 'test', password: 'pwd'}"

db:
 dbConnectionName: test connection string here
 dbHost: 127.0.09
 dbPort: 1201

management.endpoints.web.exposure.include: "*"

spring.cloud.config.uri: http://localhost:8888